### ISSUE TITLE
More file structure improvements

### ISSUE THREAD

**Issue by yzen** [logiclord/epubReader#11]
Hi Gaurav,
- I was wondering if it is necessary to duplicate some of the templates specific to UIOptions. I noticed you have non-epub templates in html/uiOptions folder that are also present in the "proper" location infusion/components/uiOptions/html.
- Also, you still have JSZip and Infusion at the top level, rather than in lib folder, I think it makes sense to group those in there.

**Comment by logiclord** [comment]
Hi Yura,

I will be cleaning of directory structure in my next commit. I kept most of
those templates while experimenting with UI Options. I really don't need
layout and link template while I am using same Textual template as in
infusion, rest are of my own.

I will ping you when I am done so that you can review most updated code.

On Thu, Jul 5, 2012 at 7:26 PM, Yura Zenevich <
reply@reply.github.com

> wrote:
> 
> Hi Gaurav,
> - I was wondering if it is necessary to duplicate some of the templates
>   specific to UIOptions. I noticed you have non-epub templates in
>   html/uiOptions folder that are also present in the "proper" location
>   infusion/components/uiOptions/html.
> - Also, you still have JSZip and Infusion at the top level, rather than in
>   lib folder, I think it makes sense to group those in there.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/logiclord/web-based-epub-reader/issues/11

## 

Regards,

Gaurav Aggarwal
Final year Student,
Delhi College of Engineering

**Comment by yzen** [comment]
Great, I just had some time to check it out and give some suggestions. I like what you did with the component structure in the epub reader code, by the way!

**Comment by logiclord** [comment]
I have changed the file structure. Please confirm about new file structure.
